---
- name: Get docker-compose file from github
  get_url: url={{ git_url }} dest={{ microservice_home }}

- name: Remove git directory and contents
  file:
    path={{ git_dest }}
    state=absent
- name: Pull docker images
  command: docker-compose pull chdir={{ microservice_home }}

- name: Start the docker services
  command: docker-compose -f docker-compose.yml up -d  chdir={{ microservice_home }}
