version: '2'
services:
  eureka:
    image: andon/eureka
    ports:
      - "8761:8761"
    networks:
      - front-tier

  customer:
    image: andon/customer
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

  catalog:
    image: andon/catalog
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

  order:
    image: andon/order
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

  zuul:
    image: andon/zuul
    ports:
      - "8080:8080"
    networks:
      - front-tier

  demodb: 
    image: mongo:3.5.5
    ports:
      - "27017:27017"
    networks:
      - back-tier
    volumes:
      - db-data:/data/db
      - db-data2:/data/configdb

volumes:
  db-data:
  db-data2:

networks:
  front-tier:
  back-tier:  

