version: '2'
services:
  eureka:
    image: andon/eureka
    expose:
      - "8761"
  customer:
    image: andon/customer
    links:
     - eureka
    expose:
    - "8080"
  catalog:
    image: andon/catalog
    links:
     - eureka
    expose:
    - "8080"
  order:
    image: andon/order
    links:
     - eureka
    expose:
    - "8080"
  zuul:
    image: andon/zuul
    links:
     - eureka
    ports:
      - "8080:8080"
  demodb: 
    image: mongo:3.5.5
    expose: 
     - "27017"
#  turbine:
#    image: eekamak/turbine
#    links:
#     - eureka
#    expose:
#      - "8989"
