---
- hosts: localhost
  connection: local
  vars:
    - hostname: "demo"
    - tds_username: "{{ lookup('env','tds_username') }}"
    - tds_password: "{{ lookup('env','tds_password') }}"
    - tenant_id: "{{lookup('env','tenant_id')}}"
    - tds_url: https://backend.mgt.tds.tieto.com

  tasks:

  - include: tasks/login.yml
  - include: tasks/get-instance.yml

  - debug: msg="Instance id is {{entity_id}}"

  - name: Delete Instance from Tieto Public TDS
    uri:
      url: "{{tds_url}}/tenants/{{tenant_id}}/instances/{{entity_id}}"
      validate_certs: False
      method: DELETE
      headers: {Authentication: "{{ auth_token }}"}
      when: entity_id is defined
