---
- hosts: localhost
  connection: local
  vars:
    - hostname: "demo"
    - tds_username: "{{ lookup('env','tds_username') }}"
    - tds_password: "{{ lookup('env','tds_password') }}"
    - tenant_id: "{{lookup('env','tenant_id')}}"
    - tds_url: https://backend.mgt.tds.tieto.com
    - ssh_rsa_key: "{{lookup('env','ssh_rsa_key')}}"
    - ssh_user: "{{lookup('env','ssh_user')}}"

  tasks:

  - include: tasks/login.yml
  - include: tasks/get-instance.yml

  - name: Deploy Ubuntu instance to Tieto Public TDS
    uri:
      url: "{{ tds_url }}/tenants/{{ tenant_id }}/instances"
      validate_certs: False
      method: POST
      body: "{{ lookup('template','ubuntuDocker.json') | to_json }}"
      headers:
        Authentication: "{{ auth_token }}"
        Content-Type: "application/json"
      timeout: 60
      return_content: yes
    when: entity_id is undefined
    register: json_response

  - set_fact:
      entity_id: "{{ (json_response.content|from_json)[0]['entityid'] }}"
    when: json_response.content is defined

  - include: tasks/wait-for-instance.yml
